mgt/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Name			:	
# Description	:	
# Author		: Sven Hergenhahn
#
# $Id$
# 
###################################################

from django.conf.urls import patterns, url
from mgt import views

urlpatterns = patterns('mgt.views', 
    url(r'^$', 'index'), 
    url(r'^range/(?P<range>\d+)/$', 'range'), 
    url(r'^range/(?P<range>\d+)/add/$', 'ip_add'), 
    #url(r'^ip/$', 'ip'), 
    url(r'^ip/(?P<pk>\d+)$', views.IpDetailView.as_view(), name='ip_detail'), 
    url(r'^ip/(?P<ip_id>\d+)/edit$', 'ip_edit'), 
    url(r'^ip/(?P<ip_id>\d+)/del$', 'ip_delete'), 
    url(r'^host/(?P<pk>\d+)$', views.HostDetailView.as_view(), name='host_detail'), 
    url(r'^host/(?P<pk>\d+)/edit$', views.HostUpdateView.as_view(), name='host_edit'), 
    url(r'^host/(?P<pk>\d+)/del$', views.HostDeleteView.as_view(), name='host_delete'), 
)

urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ip/',   include('ip.urls')),

    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

ip/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from mptt.models import MPTTModel, TreeForeignKey
from ipaddress import ip_address, ip_network

STATUS_CHOICES = ( 
    ('active', 'Aktiv'),
    ('inactive', 'Inaktiv'),
    ('planned', 'Geplant'),
    ('unknown', 'Unbekannt'),
    ('reserved', 'Reserviert'),
    ('blocked', 'Blockiert'),
)

IFACE_CHOICES = tuple([ (i,i) for i in range(11)])


class Netgroup(models.Model):
    name = models.CharField('Name', max_length=200)
    parent = models.ManyToManyField('self', null=True, blank=True)
    description = models.CharField('Beschreibung', max_length=200)

    def __unicode__(self):
        return self.name
    created = models.DateField(auto_now=True, null=True)
    modified = models.DateField(auto_now=True, null=True)


class Network(MPTTModel):
    name = models.GenericIPAddressField(
        'Netzwerk ID', help_text="Please use the following format: <em>xxx.xxx.xxx.xxx</em>.")
    cidr = models.IntegerField(
        'CIDR Maske', validators=[MaxValueValidator(128)])
    type = models.CharField(
        'Typ', max_length=20, choices=(('subnet','Netzwerk'),('netblock','Netzblock')),
        help_text="Block - ordnet nur; Netz - enthält Adressen")
    description = models.CharField(
        'Beschreibung', max_length=200)
    comment = models.CharField(
        'Kommentar', max_length=200, blank=True)
    parent = TreeForeignKey('self', null=True, blank=True,
                               related_name='subnets',
                                limit_choices_to = { 'type':'netblock'})
    netgroup = models.ManyToManyField(Netgroup, null=True, blank=True,
        verbose_name='Net Group' )
    vlan = models.ForeignKey(
        'Vlan', null=True, blank=True)
    def_net_size= models.IntegerField(
         'default net size', validators=[MaxValueValidator(128)], blank=True, null=True)
    def_alloc_size= models.IntegerField(
         'default allocation size', validators=[MaxValueValidator(128)], blank=True, null=True)

    def __unicode__(self):
        return '/'.join([self.name, str(self.cidr)])

    def clean(self):
        # make sure the network/netblock is contained in its parent
        if self.parent:
            try:
                for a_net in ip_network(
                                    unicode(self.parent)
                                ).address_exclude(
                                    ip_network(
                                        unicode(
                                            '/'.join(
                                                        [self.name, str(self.cidr)]
                                                    )
                                        )
                                    )
                                ):
                    pass
            except ValueError, e:
                raise ValidationError(e)
    created = models.DateField(auto_now=True, null=True)
    modified = models.DateField(auto_now=True, null=True)


class Range(models.Model):
    parent = models.ForeignKey(Network, limit_choices_to = {'type':'subnet'})
    description = models.CharField(
        'Beschreibung', max_length=200)
    comment = models.CharField(
        'Kommentar', max_length=200, blank=True)
    start_ip = models.GenericIPAddressField(
        'Start IP', help_text="Please use a valid IPv4 or IPv6 format.")
    stop_ip = models.GenericIPAddressField(
        'Stop IP', help_text="Please use a valid IPv4 or IPv6 format.")

    def __unicode__(self):
        return '-'.join([self.start_ip, self.stop_ip])

    def get_next_known(self):
        '''Return the next known address in this range as IpAddress object.
           Known means that is is in the DB, but with states like unknown,
           reserved, blocked
        '''
        q = IpAddress.objects.filter(
            range__id=self.pk).filter(
                status__in=[
                    'unknown', 
                    'reserved', 
                    'blocked']
            ).order_by('address')
        return q[0]

    def get_next_free(self):
        '''Return the next free address in this range as String '''
        used_addresses = IpAddress.objects.filter(
            range__id=self.pk).order_by('address')
        addr_list = [ o.address for o in used_addresses ]
        net = ip_network(self.parent)
        start = ip_address(self.start_ip)
        stop = ip_address(self.stop_ip)
        for x in net.hosts():
            if x < start: continue
            if str(x) in addr_list:
                continue
            if x > stop: break
            return str(x)
        return 'No more free addresses avaliable!'

    def clean(self):
        '''Validate start and stop addresses as valid addresses of the network'''
        net = ip_network(self.parent)
        start = ip_address(self.start_ip)
        stop = ip_address(self.stop_ip)
        if start not in net:
            raise ValidationError('Start IP not in net')
        elif stop not in net:
            raise ValidationError('Stop IP not in net')
        elif self.stop_ip < self.start_ip:
            raise ValidationError('Order of start/stop IP is wrong')
    created = models.DateField(auto_now=True, null=True)
    modified = models.DateField(auto_now=True, null=True)


class Vlan(models.Model):
    vlan_id = models.IntegerField()
    name = models.CharField(
        'Vlan Name', max_length=200)

    def __unicode__(self):
        return "%s (%d)" % (self.name, self.vlan_id)
    created = models.DateField(auto_now=True, null=True)
    modified = models.DateField(auto_now=True, null=True)


class Host(models.Model):
    name = models.CharField(
        'Hostname', max_length=200)
    created = models.DateField(auto_now=True, null=True)
    modified = models.DateField(auto_now=True, null=True)

    def __unicode__(self):
        return self.name


class IpAddress(models.Model):
    range = models.ForeignKey(Range)
    address = models.GenericIPAddressField('IP Addresse') 
    interface = models.IntegerField('Interface Nummer', choices=IFACE_CHOICES,
                                    help_text='# of the interface (0-n)',
                                    blank = True,
                                    null=True)
    base_interface = models.BooleanField('Basis-Interface?', default=False)
    global_interface = models.BooleanField('Global generieren?', default=False)
    name = models.CharField('Interface Name', help_text='DNS-Name up to "company".de', max_length=50, blank=True)
    host = models.ManyToManyField(Host, verbose_name='hostname', 
                                  help_text='FQDN de(r|s) Hosts, der das Interface bekommt', 
                                  blank=True)
    purpose = models.CharField('Zweck', max_length=200, blank=True)
    status = models.CharField('Status', choices=STATUS_CHOICES, max_length=20)
    config = models.CharField('Config Info', max_length=200, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)

    def __unicode__(self):
        return self.address
    
    def clean(self):
        # make sure the address is within the selected range
        if self.address:
            if ip_address(unicode(self.address)) < ip_address(unicode(self.range.start_ip)):
                raise ValidationError('Address is below chosen range')
            elif ip_address(unicode(self.address)) > ip_address(unicode(self.range.stop_ip)):
                raise ValidationError('Address is above chosen range')

mgt/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Name			:	
# Description	:	
# Author		: Sven Hergenhahn
#
# $Id$
# 
###################################################


from mgt.models import Netgroup, Network, Range, IpAddress
from django.forms import ModelForm

class Ip4AddressForm(ModelForm):
    class Meta:
        model=IpAddress
        #fields = [ 'address', 'name', 'host', 'interface', 'status', 'range', 'purpose' ]

mgt/views.py
# Create your views here.
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.views import generic
from mgt.models import Netgroup, Network, Range, IpAddress, Host
import forms
from django.shortcuts import get_object_or_404
import socket, struct

from pprint import pprint

def dottedQuadToNum(ip):
    "convert decimal dotted quad string to long integer"
    return struct.unpack('L',socket.inet_aton(ip))[0]


def index(request):
    net_list = Network.objects.all().order_by('id')
    return render_to_response('mgt/index.html', {'net_list': net_list,})

def ip_edit(request, ip_id=None):
    if request.POST:
        if ip_id:
            ip_data = get_object_or_404(IpAddress, pk=ip_id)
            form = forms.Ip4AddressForm(instance=ip_data, data=request.POST)
        else:
            form = forms.Ip4AddressForm(data=request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/mgt/')
    else:
        if ip_id:
            ip_data = get_object_or_404(IpAddress, pk=ip_id)
            form =  forms.Ip4AddressForm(instance=ip_data)
        else:
            form =  forms.Ip4AddressForm()

    return render_to_response('mgt/ip.html', {'form':form}, context_instance=RequestContext(request)) 

class IpDetailView(generic.DetailView):
    model = IpAddress

def ip_add(request, range=None):
    if request.POST:
        form = forms.Ip4AddressForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/mgt/')
        else:
            return render_to_response('mgt/ip.html', {'form':form}, context_instance=RequestContext(request)) 
    elif range:
        form = forms.Ip4AddressForm(initial={ 'range':range })
        return render_to_response('mgt/ip.html', {'form':form}, context_instance=RequestContext(request)) 

def ip_delete(request, ip_id=None):
        ip_obj = get_object_or_404(IpAddress, pk=ip_id)
        ip_obj.delete()
        return HttpResponseRedirect('/mgt/')

def range(request, range):
    ip_list = IpAddress.objects.filter(range__id=range)
    range_data = Range.objects.filter(pk=range)[0]
    return render_to_response('mgt/range.html', {'ip_list': ip_list,
                                                 'range':range_data})

class HostDetailView(generic.DetailView):
    model = Host

class HostUpdateView(generic.UpdateView):
    model = Host

class HostDeleteView(generic.DeleteView):
    model = Host

mgt/templates/mgt/host_detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'mgt/formate.css' %}" />

<h3>Host {{ host.name }}</h3>
<table>
    <tr>
        <td style="background-color:silver"><a href="{% url 'host_edit' host.id %}">&Auml;ndern</a></td>
        <td style="background-color:silver"><a href="{% url 'host_delete' host.id %}"  onclick="return confirm('Wirklich den Host löschen?');">L&ouml;schen</a></td>
    </tr>
</table>
<br>
<h2>{{ host.name }}</h2>
<h3>Interfaces</h3>
<ul>
{% if host.ipaddress_set.all %}
{% for ipaddress in host.ipaddress_set.all %}
    <li><a href="{% url 'ip_detail'  ipaddress.id %}">{{ ipaddress.address }}</a> - {{ipaddress.name}}) ({{ipaddress.status}})</li>
{% endfor %}
{% else %}
    <li>Keine Interfaces bisher.
{% endif %}
</ul>

<hr>
<table class="metadate">
<tr>
<td>erstellt</td><td>{{ host.created }}</td>
</tr>
<tr>
<td>zuletzt ge&auml;ndert</td><td>{{ host.modified }} (vor {{ host.modified|timesince }})</td>
</tr>
</table>
<hr>

mgt/templates/mgt/index.html
{% load mptt_tags %}
{% load staticfiles %}
{% load ip_filter %}

<link rel="stylesheet" type="text/css" href="{% static 'mgt/formate.css' %}">
<script type="text/javascript" src="{% static 'mgt/jquery.js' %}"></script>

<script type="text/javascript">
$(document).ready(function() {

		// Toggle visibility of sub-elements
		$("div.tree table").click(function() {
				$(this).parent().children().filter('div').toggle('fast');
		});
		// Toggle visibility of ip table
		$("tr.range").click(function() {
				$(this).parent().parent().next().toggle('fast');
		});
});

</script>

<body class="defaults">

<h3>The Denic Network Tree</h3>


  {% recursetree net_list %}
  <div class="tree tree-indent-{{node.level}}">
		<table class="tree-all">
			<tr class="{{node.type}}">
				<td class="tw-{{node.level}}">{{ node.name }}/{{ node.cidr }}</td>
				<td>{{ node.description }}</td>
	 	    </tr>
	    </table>
	{% for range in node.range_set.all %}
   <div class="tree tree-indent-1">
	   <table class="tree-all">
		   <tr class="range">
			  <td class="tw-{{node.level|add:'1'}}">{{range.description}}</td>
			  <td>{{range.comment}}</td>
			</tr>
	  </table>
      <table class='iptable'>
  		{% for addr in range.ipaddress_set.all %}
  		{% if forloop.first %}
  		<tr class="tree-all tree-subhead">
    		<td style="width:60px;">
      			<a href="/mgt/range/{{ range.id }}/add/">
					<img src="{% static "mgt/images/add.gif" %}" title="add" align="right"/>
      			</a>
    		</td>
    		<td style="width:30px;">IP</td>
    		<td class="tree-status" style="width:15px;"></td>

    		<td style="width:150px;">iface name</td>
    		<td style="width:150px;">hosts</td>
    		<td style="width:30px;">i/f #</td>
    		<td style="width:250px;">config</td>
    		<td style="width:250px;">comments</td>
  		</tr>
  		{% endif %}
  		<tr class="tree-all">
      		<td class="tree-indent" style="text-align:right;">
       			<a href="/mgt/ip/{{ addr.id }}/edit"><img src="{% static "mgt/images/edit.gif" %}" title="edit" /></a>
       			<a href="/mgt/ip/{{ addr.id }}/del"  onclick="return confirm('Wirklich die IP Adresse {{ addr.address }} l&ouml;schen?');"><img src="{% static "mgt/images/del.gif" %}" title="delete" /></a>
      		</td>
            <td class="tree-ip"><a href="/mgt/ip/{{ addr.id }}">{{ addr.address|last_part:'1' }}</a></td>
    		<td class="tree-ip tree-status"><img src="{% static "mgt/images/"|add:addr.status|add:'.gif' %}" title="{{addr.status}}"/></td>
			<td class="tree-ip">{{ addr.name }}</td>
            <td class="tree-ip">
                {% for host in addr.host.all %}
  		            {% if not forloop.first %}
                    , 
                    {% endif %}
                    {{ host.name|uqdn}}
                {% endfor %}
            </td>
			<td class="tree-ip">{{ addr.interface }}</td>
			<td class="tree-ip"></td>
			<td class="tree-ip">{{ addr.purpose }}</td>
	  	</tr>
    {% empty %}
  		<tr class="tree-all">
      		<td class="tree-indent" colspan=8>
        		<a href="/mgt/range/{{ range.id }}/add/">
          			<img src="{% static "mgt/images/add.gif" %}" title="add"/>
        		</a>
      		</td>
		</tr>
  	{% endfor %}
      </table>
  </div>
 	{% endfor %}
{% if not node.is_leaf_node %}
{{ children }}
{% endif %}
</div>
{% endrecursetree %}

mgt/templates/mgt/ipaddress_detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'mgt/formate.css' %}" />

<h3>IP Adresse {{ ipaddress.address }} - Details</h3>
<table>
    <tr>
        <td style="background-color:silver"><a href="{{ipaddress.id }}/edit">&Auml;ndern</a></td>
        <td style="background-color:silver"><a href="{{ipaddress.id }}/del"  onclick="return confirm('Wirklich die IP- Adresse löschen?');">L&ouml;schen</a></td>
    </tr>
</table>
<br>
<table>
    <tr>
        <th>Adresse</th>
        <td>{{ ipaddress.address }}</td>
    </tr>
    <tr>
        <th>Interface Name</th>
        <td>{{ ipaddress.name }}</td>
    </tr>
    <tr>
        <th>Status</th>
        <td>{{ ipaddress.status }}</td>
    </tr>
<tr>
    <th>Netzwerk</th>
    <td>{{ ipaddress.range.parent.name }}/{{ipaddress.range.parent.cidr }}</td>
    <td>{{ ipaddress.range.parent.comment }}</td>
</tr>
<tr>
    <th>VLan</th>
    <td>{{ ipaddress.range.parent.vlan }}</td>
</tr>
<tr>
    <th>Range</th>
    <td>{{ ipaddress.range.description }}</td>
    <td>{{ ipaddress.range.comment }}</td>
</tr>
    <tr>
        <th>Interface-Typ</th>
        <td>
            {% if ipaddress.base_interface %}
                Basis Interface
            {% else %}
                Service Interface
            {% endif %}
        </td>
    </tr>
    <tr>
        <th>Global?</th>
        <td>
            {% if ipaddress.global_interface %}
                Ja
            {% else %}
                Nein
            {% endif %}
        </td>
    </tr>
    <tr>
        <th>Zweck</th>
        <td colspan=2>{{ ipaddress.purpose }}</td>
    </tr>
    <tr>
        <th>Konfig-Info</th>
        <td colspan=2>{{ ipaddress.config }}</td>
    </tr>
</table>
<hr>
<h3>Hosts</h3>
<ul>
{% if ipaddress.host.all %}
{% for host in ipaddress.host.all %}
    <li><a href="{% url 'host_detail' host.id %}">{{ host.name }}</a> (i/f# {{ipaddress.interface}})</li>
{% endfor %}
{% else %}
    <li>Dieses Interface ist f&uuml;r keinen Host konfiguriert.
{% endif %}
</ul>

<hr>
<table class="metadate">
<tr>
<td>erstellt</td><td>{{ ipaddress.created }}</td>
</tr>
<tr>
<td>zuletzt ge&auml;ndert</td><td>{{ ipaddress.modified }} (vor {{ ipaddress.modified|timesince }})</td>
</tr>
</table>
<hr>